const District = [
    "Dhaka",
    "Faridpur",
    "Gazipur",
    "Gopalganj",
    "Jamalpur",
    "Kishoreganj",
    "Madaripur",
    "Manikganj",
    "Munshiganj",
    "Mymensingh",
    "Narayanganj",
    "Narsingdi",
    "Netrokona",
    "Rajbari",
    "Shariatpur",
    "Sherpur",
    "Tangail",
    "Bogra",
    "Joypurhat",
    "Naogaon",
    "Natore",
    "Nawabganj",
    "Pabna",
    "Rajshahi",
    "Sirajgonj",
    "Dinajpur",
    "Gaibandha",
    "Kurigram",
    "Lalmonirhat",
    "Nilphamari",
    "Panchagarh",
    "Rangpur",
    "Thakurgaon",
    "Barguna",
    "Barisal",
    "Bhola",
    "Jhalokati",
    "Patuakhali",
    "Pirojpur",
    "Bandarban",
    "Brahmanbaria",
    "Chandpur",
    "Chittagong",
    "Comilla",
    "Cox's Bazar",
    "Feni",
    "Khagrachari",
    "Lakshmipur",
    "Noakhali",
    "Rangamati",
    "Habiganj",
    "Maulvibazar",
    "Sunamganj",
    "Sylhet",
    "Bagerhat",
    "Chuadanga",
    "Jessore",
    "Jhenaidah",
    "Khulna",
    "Kushtia",
    "Magura",
    "Meherpur",
    "Narail",
    "Satkhira"
]

const Bank = [
    "AB Bank",
    "Agrani Bank",   
    "Al-Arafah Islami Bank",
    "Bangladesh Commerce Bank",
    "Bangladesh Development Bank",
    "Bangladesh Krishi Bank",
    "Bank Alfalah",
    "Bank Asia",
    "Bangladesh Small Industries and Commerce Bank",
    "Bengal Commercial Bank",
    "BRAC Bank",
    "Citibank N.A",
    "The City Bank",
    "Commercial Bank of Ceylon",
    "Community Bank Bangladesh",
    "Dhaka Bank",
    "Dutch-Bangla Bank",
    "Eastern Bank",
    "Export Import Bank of Bangladesh",
    "First Security Islami Bank",
    "Global Islami Bank",
    "Habib Bank",
    "The Hongkong and Shanghai Banking Corporation",
    "ICB Islamic Bank",
    "International Finance Invest and Commerce Bank",
    "Islami Bank Bangladesh",
    "Jamuna Bank",
    "Janata Bank",
    "Meghna Bank",
    "Mercantile Bank",
    "Midland Bank",
    "Modhumoti Bank",
    "Mutual Trust Bank",
    "National Bank",
    "National Bank of Pakistan",
    "National Credit & Commerce Bank",
    "NRB Bank",
    "NRB Commercial Bank",
    "One Bank",
    "Padma Bank",
    "The Premier Bank",
    "Prime Bank",
    "Probashi Kallyan Bank",
    "Pubali Bank",
    "Rajshahi Krishi Unnayan Bank",
    "Rupali Bank",
    "South Bangla Agriculture & Commerce Bank",
    "Shahjalal Islami Bank",
    "Shimanto Bank",
    "Social Islami Bank",
    "Sonali Bank",
    "Southeast Bank",
    "Standard Bank",
    "Standard Chartered Bank",
    "State Bank of India",
    "Trust Bank",
    "Union Bank",
    "United Commercial Bank",
    "Uttara Bank",
    "Woori Bank Bangladesh",
]

export const DistrictData = District.map((district) => ({
    value: district,
    label: district,
}));

export const BankData = Bank.map((bank) => ({
    value: bank,
    label: bank,
}));

export interface Option {
    value: string;
    label: string;
}