# Generated by Django 4.2.5 on 2023-10-17 16:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.CharField(max_length=255, null=True)),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('est_year', models.CharField(max_length=10, null=True)),
                ('origin', models.CharField(choices=[('Local Bank', 'Local Bank'), ('Foreign Bank', 'Foreign Bank')], default='Local Bank', max_length=20)),
                ('hotline', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('bank_code', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankCategory',
            fields=[
                ('bank_category', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankType',
            fields=[
                ('bank_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('internal_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('credit_limit', models.CharField(max_length=100, null=True)),
                ('apr', models.CharField(max_length=100, null=True)),
                ('introductory_apr', models.CharField(max_length=100, null=True)),
                ('foreign_transaction_fee', models.CharField(max_length=100, null=True)),
                ('late_payment_fee', models.CharField(max_length=100, null=True)),
                ('over_limit_fee', models.CharField(max_length=100, null=True)),
                ('billing_cycle', models.CharField(max_length=256, null=True)),
                ('issuance_fee', models.CharField(max_length=100, null=True)),
                ('annual_fee', models.CharField(max_length=100, null=True)),
                ('grace_period', models.CharField(max_length=150, null=True)),
                ('customer_ratings', models.CharField(max_length=100, null=True)),
                ('supplementary_card_number', models.IntegerField(null=True)),
                ('supplementary_card_allowed', models.BooleanField(null=True)),
                ('tags', models.CharField(max_length=150, null=True)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='bankingapp.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('card_category', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardNetwork',
            fields=[
                ('card_network', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardUsage',
            fields=[
                ('card_usage', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepositSchemeName',
            fields=[
                ('deposit_scheme_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepositSchemeType',
            fields=[
                ('deposit_scheme_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoanName',
            fields=[
                ('loan_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('loan_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_name', models.CharField(max_length=100)),
                ('descriptoin', models.TextField()),
                ('tags', models.CharField(max_length=50)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_offer', to='bankingapp.card')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('loan_min_limit', models.IntegerField()),
                ('loan_max_limit', models.BigIntegerField()),
                ('interest_rate', models.FloatField()),
                ('grace_period', models.DateTimeField()),
                ('hidden_charge', models.BooleanField()),
                ('interest_type', models.CharField(choices=[('Simple', 'Simple'), ('Compound', 'Compound')], default='Simple', max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('feature', models.CharField(max_length=300)),
                ('learn_more_link', models.CharField(max_length=50)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='bankingapp.bank')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='bankingapp.loanname')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='bankingapp.loantype')),
            ],
        ),
        migrations.CreateModel(
            name='DepositScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('learn_more_link', models.CharField(max_length=255)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='bankingapp.bank')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='bankingapp.depositschemename')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='bankingapp.depositschemetype')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit', to='bankingapp.benefits')),
                ('credit_card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_benefit', to='bankingapp.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='bankingapp.cardcategory'),
        ),
        migrations.AddField(
            model_name='card',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='bankingapp.cardnetwork'),
        ),
        migrations.AddField(
            model_name='card',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='bankingapp.cardusage'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.CharField(max_length=255, null=True)),
                ('routing_number', models.CharField(max_length=255, null=True)),
                ('address_line', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('district', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('swift_code', models.CharField(max_length=20, null=True)),
                ('opening_time', models.CharField(max_length=10, null=True)),
                ('closing_time', models.CharField(max_length=10, null=True)),
                ('location_latitude', models.FloatField(null=True)),
                ('location_longitude', models.FloatField(null=True)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='bankingapp.bank')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='bankingapp.bankcategory'),
        ),
        migrations.AddField(
            model_name='bank',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='bankingapp.banktype'),
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('district', models.CharField(max_length=20, null=True)),
                ('location_latitude', models.FloatField(null=True)),
                ('location_longitude', models.FloatField(null=True)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atm', to='bankingapp.bank')),
            ],
        ),
    ]
