# Generated by Django 4.2.5 on 2024-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='grace_period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.CharField(max_length=10),
        ),
    ]
