# Generated by Django 4.2.4 on 2024-01-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_alter_branch_email_alter_loan_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='grace_period',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.CharField(max_length=20),
        ),
    ]
