# Generated by Django 4.2.4 on 2024-01-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_alter_loan_grace_period_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanname',
            name='loan_name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
