# Generated by Django 4.2.4 on 2024-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_alter_loanname_loan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
