# Generated by Django 4.2.4 on 2024-01-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0005_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='feature',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='hidden_charge',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='learn_more_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
