# Generated by Django 4.2.4 on 2024-01-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0006_alter_loan_duration_alter_loan_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='grace_period',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_max_limit',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_min_limit',
            field=models.IntegerField(null=True),
        ),
    ]
